# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/boram/Desktop/kernel_filtering/kernel_filtering.srcs/sources_1/ip/buffer_ram_2/buffer_ram_2.xci
# IP: The module: 'buffer_ram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/boram/Desktop/kernel_filtering/kernel_filtering.gen/sources_1/ip/buffer_ram_2/buffer_ram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'buffer_ram_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/boram/Desktop/kernel_filtering/kernel_filtering.srcs/sources_1/ip/buffer_ram_2/buffer_ram_2.xci
# IP: The module: 'buffer_ram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/boram/Desktop/kernel_filtering/kernel_filtering.gen/sources_1/ip/buffer_ram_2/buffer_ram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'buffer_ram_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
